-- ================================================================================
-- DOMAIN 5: DATA GOVERNANCE & PRIVACY - ALL 40 QUESTIONS
-- ================================================================================
-- Generated: December 18, 2025
-- Complete: 40 questions with full metadata
-- ================================================================================

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Policy Framework', 'D5-Q001', 'Does your organization have a comprehensive data governance policy that specifically addresses AI systems?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No data governance policy in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data governance policy in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Governance Policy exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data governance policy with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data governance policy with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data governance policy maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data governance policy; ad hoc approach", "level_2": "Basic data governance policy in development", "level_3": "Data Governance Policy exists but gaps remain", "level_4": "Comprehensive data governance policy well-implemented", "level_5": "Industry-leading data governance policy with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Classification', 'D5-Q002', 'Are data classification frameworks in place that categorize AI training data, model data, and inference data?', 'HIGH', 1.0, '[{"value": 1, "label": "No data classification in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data classification in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Classification exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data classification with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data classification with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data classification maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data classification; ad hoc approach", "level_2": "Basic data classification in development", "level_3": "Data Classification exists but gaps remain", "level_4": "Comprehensive data classification well-implemented", "level_5": "Industry-leading data classification with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q003', 'Do you have documented data retention and deletion policies specifically for AI systems?', 'HIGH', 1.0, '[{"value": 1, "label": "No data retention & deletion in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data retention & deletion in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Retention & Deletion exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data retention & deletion with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data retention & deletion with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data retention & deletion maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data retention & deletion; ad hoc approach", "level_2": "Basic data retention & deletion in development", "level_3": "Data Retention & Deletion exists but gaps remain", "level_4": "Comprehensive data retention & deletion well-implemented", "level_5": "Industry-leading data retention & deletion with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Assessment', 'D5-Q004', 'Are privacy impact assessments (PIAs) or data protection impact assessments (DPIAs) conducted for all AI systems processing personal data?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No privacy impact assessments in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic privacy impact assessments in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Privacy Impact Assessments exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive privacy impact assessments with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading privacy impact assessments with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating privacy impact assessments maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal privacy impact assessments; ad hoc approach", "level_2": "Basic privacy impact assessments in development", "level_3": "Privacy Impact Assessments exists but gaps remain", "level_4": "Comprehensive privacy impact assessments well-implemented", "level_5": "Industry-leading privacy impact assessments with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Subject Rights', 'D5-Q005', 'Do you have mechanisms in place to honor data subject rights (access, rectification, erasure, portability) for data used in AI systems?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No data subject rights in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data subject rights in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Subject Rights exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data subject rights with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data subject rights with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data subject rights maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data subject rights; ad hoc approach", "level_2": "Basic data subject rights in development", "level_3": "Data Subject Rights exists but gaps remain", "level_4": "Comprehensive data subject rights well-implemented", "level_5": "Industry-leading data subject rights with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q006', 'Is explicit informed consent obtained for all data collection used in AI training and operation?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No data collection consent in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data collection consent in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Collection Consent exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data collection consent with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data collection consent with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data collection consent maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data collection consent; ad hoc approach", "level_2": "Basic data collection consent in development", "level_3": "Data Collection Consent exists but gaps remain", "level_4": "Comprehensive data collection consent well-implemented", "level_5": "Industry-leading data collection consent with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q007', 'Are data quality assurance processes in place for AI system inputs and training data?', 'HIGH', 1.0, '[{"value": 1, "label": "No data quality assurance in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data quality assurance in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Quality Assurance exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data quality assurance with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data quality assurance with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data quality assurance maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data quality assurance; ad hoc approach", "level_2": "Basic data quality assurance in development", "level_3": "Data Quality Assurance exists but gaps remain", "level_4": "Comprehensive data quality assurance well-implemented", "level_5": "Industry-leading data quality assurance with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q008', 'Do you maintain comprehensive data lineage tracking for AI systems?', 'HIGH', 1.0, '[{"value": 1, "label": "No data lineage tracking in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data lineage tracking in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Lineage Tracking exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data lineage tracking with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data lineage tracking with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data lineage tracking maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data lineage tracking; ad hoc approach", "level_2": "Basic data lineage tracking in development", "level_3": "Data Lineage Tracking exists but gaps remain", "level_4": "Comprehensive data lineage tracking well-implemented", "level_5": "Industry-leading data lineage tracking with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q009', 'Are data versioning controls implemented for AI training datasets and model inputs?', 'HIGH', 1.0, '[{"value": 1, "label": "No data versioning in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data versioning in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Versioning exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data versioning with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data versioning with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data versioning maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data versioning; ad hoc approach", "level_2": "Basic data versioning in development", "level_3": "Data Versioning exists but gaps remain", "level_4": "Comprehensive data versioning well-implemented", "level_5": "Industry-leading data versioning with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Lifecycle', 'D5-Q010', 'Do you have secure archival and backup procedures for AI system data?', 'HIGH', 1.0, '[{"value": 1, "label": "No data archival & backup in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data archival & backup in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Archival & Backup exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data archival & backup with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data archival & backup with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data archival & backup maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data archival & backup; ad hoc approach", "level_2": "Basic data archival & backup in development", "level_3": "Data Archival & Backup exists but gaps remain", "level_4": "Comprehensive data archival & backup well-implemented", "level_5": "Industry-leading data archival & backup with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Controls', 'D5-Q011', 'Is privacy-by-design integrated into AI system development from inception?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No privacy by design in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic privacy by design in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Privacy by Design exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive privacy by design with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading privacy by design with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating privacy by design maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal privacy by design; ad hoc approach", "level_2": "Basic privacy by design in development", "level_3": "Privacy by Design exists but gaps remain", "level_4": "Comprehensive privacy by design well-implemented", "level_5": "Industry-leading privacy by design with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Controls', 'D5-Q012', 'Do you practice data minimization principles in AI system design and operation?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No data minimization in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data minimization in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Minimization exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data minimization with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data minimization with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data minimization maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data minimization; ad hoc approach", "level_2": "Basic data minimization in development", "level_3": "Data Minimization exists but gaps remain", "level_4": "Comprehensive data minimization well-implemented", "level_5": "Industry-leading data minimization with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Controls', 'D5-Q013', 'Are purpose limitation controls enforced for AI data processing activities?', 'HIGH', 1.0, '[{"value": 1, "label": "No purpose limitation in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic purpose limitation in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Purpose Limitation exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive purpose limitation with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading purpose limitation with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating purpose limitation maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal purpose limitation; ad hoc approach", "level_2": "Basic purpose limitation in development", "level_3": "Purpose Limitation exists but gaps remain", "level_4": "Comprehensive purpose limitation well-implemented", "level_5": "Industry-leading purpose limitation with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Controls', 'D5-Q014', 'Do you employ robust anonymization or pseudonymization techniques for AI training data?', 'HIGH', 1.0, '[{"value": 1, "label": "No anonymization techniques in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic anonymization techniques in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Anonymization Techniques exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive anonymization techniques with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading anonymization techniques with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating anonymization techniques maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal anonymization techniques; ad hoc approach", "level_2": "Basic anonymization techniques in development", "level_3": "Anonymization Techniques exists but gaps remain", "level_4": "Comprehensive anonymization techniques well-implemented", "level_5": "Industry-leading anonymization techniques with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Privacy Controls', 'D5-Q015', 'Are differential privacy or similar privacy-preserving techniques used in AI systems?', 'HIGH', 1.0, '[{"value": 1, "label": "No differential privacy in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic differential privacy in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Differential Privacy exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive differential privacy with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading differential privacy with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating differential privacy maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal differential privacy; ad hoc approach", "level_2": "Basic differential privacy in development", "level_3": "Differential Privacy exists but gaps remain", "level_4": "Comprehensive differential privacy well-implemented", "level_5": "Industry-leading differential privacy with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Consent Management', 'D5-Q016', 'Do you have clear, understandable informed consent mechanisms for AI data usage?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No informed consent mechanisms in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic informed consent mechanisms in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Informed Consent Mechanisms exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive informed consent mechanisms with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading informed consent mechanisms with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating informed consent mechanisms maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal informed consent mechanisms; ad hoc approach", "level_2": "Basic informed consent mechanisms in development", "level_3": "Informed Consent Mechanisms exists but gaps remain", "level_4": "Comprehensive informed consent mechanisms well-implemented", "level_5": "Industry-leading informed consent mechanisms with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Consent Management', 'D5-Q017', 'Can data subjects easily withdraw consent for AI data processing?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No consent withdrawal in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic consent withdrawal in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Consent Withdrawal exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive consent withdrawal with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading consent withdrawal with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating consent withdrawal maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal consent withdrawal; ad hoc approach", "level_2": "Basic consent withdrawal in development", "level_3": "Consent Withdrawal exists but gaps remain", "level_4": "Comprehensive consent withdrawal well-implemented", "level_5": "Industry-leading consent withdrawal with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Consent Management', 'D5-Q018', 'Do you provide granular consent options for different AI processing purposes?', 'HIGH', 1.0, '[{"value": 1, "label": "No granular consent options in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic granular consent options in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Granular Consent Options exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive granular consent options with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading granular consent options with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating granular consent options maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal granular consent options; ad hoc approach", "level_2": "Basic granular consent options in development", "level_3": "Granular Consent Options exists but gaps remain", "level_4": "Comprehensive granular consent options well-implemented", "level_5": "Industry-leading granular consent options with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Consent Management', 'D5-Q019', 'Are comprehensive audit trails maintained for all consent decisions?', 'HIGH', 1.0, '[{"value": 1, "label": "No consent audit trails in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic consent audit trails in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Consent Audit Trails exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive consent audit trails with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading consent audit trails with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating consent audit trails maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal consent audit trails; ad hoc approach", "level_2": "Basic consent audit trails in development", "level_3": "Consent Audit Trails exists but gaps remain", "level_4": "Comprehensive consent audit trails well-implemented", "level_5": "Industry-leading consent audit trails with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Consent Management', 'D5-Q020', 'Do you have processes for obtaining re-consent when AI purposes change?', 'HIGH', 1.0, '[{"value": 1, "label": "No re-consent processes in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic re-consent processes in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Re-consent Processes exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive re-consent processes with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading re-consent processes with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating re-consent processes maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal re-consent processes; ad hoc approach", "level_2": "Basic re-consent processes in development", "level_3": "Re-consent Processes exists but gaps remain", "level_4": "Comprehensive re-consent processes well-implemented", "level_5": "Industry-leading re-consent processes with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Access Controls', 'D5-Q021', 'Is role-based access control (RBAC) implemented for AI system data and models?', 'HIGH', 1.0, '[{"value": 1, "label": "No role-based access control in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic role-based access control in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Role-Based Access Control exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive role-based access control with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading role-based access control with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating role-based access control maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal role-based access control; ad hoc approach", "level_2": "Basic role-based access control in development", "level_3": "Role-Based Access Control exists but gaps remain", "level_4": "Comprehensive role-based access control well-implemented", "level_5": "Industry-leading role-based access control with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Access Controls', 'D5-Q022', 'Do you enforce least privilege principles for AI system access?', 'HIGH', 1.0, '[{"value": 1, "label": "No least privilege principle in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic least privilege principle in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Least Privilege Principle exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive least privilege principle with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading least privilege principle with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating least privilege principle maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal least privilege principle; ad hoc approach", "level_2": "Basic least privilege principle in development", "level_3": "Least Privilege Principle exists but gaps remain", "level_4": "Comprehensive least privilege principle well-implemented", "level_5": "Industry-leading least privilege principle with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Access Controls', 'D5-Q023', 'Are all access attempts to AI data and systems comprehensively logged?', 'HIGH', 1.0, '[{"value": 1, "label": "No access logging in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic access logging in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Access Logging exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive access logging with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading access logging with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating access logging maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal access logging; ad hoc approach", "level_2": "Basic access logging in development", "level_3": "Access Logging exists but gaps remain", "level_4": "Comprehensive access logging well-implemented", "level_5": "Industry-leading access logging with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Access Controls', 'D5-Q024', 'Do you conduct regular access reviews for AI systems and data?', 'HIGH', 1.0, '[{"value": 1, "label": "No access reviews in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic access reviews in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Access Reviews exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive access reviews with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading access reviews with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating access reviews maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal access reviews; ad hoc approach", "level_2": "Basic access reviews in development", "level_3": "Access Reviews exists but gaps remain", "level_4": "Comprehensive access reviews well-implemented", "level_5": "Industry-leading access reviews with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Access Controls', 'D5-Q025', 'Is privileged access to AI systems managed with enhanced controls?', 'HIGH', 1.0, '[{"value": 1, "label": "No privileged access management in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic privileged access management in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Privileged Access Management exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive privileged access management with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading privileged access management with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating privileged access management maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal privileged access management; ad hoc approach", "level_2": "Basic privileged access management in development", "level_3": "Privileged Access Management exists but gaps remain", "level_4": "Comprehensive privileged access management well-implemented", "level_5": "Industry-leading privileged access management with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Security', 'D5-Q026', 'Is all AI system data encrypted at rest using industry-standard encryption?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No encryption at rest in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic encryption at rest in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Encryption at Rest exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive encryption at rest with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading encryption at rest with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating encryption at rest maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal encryption at rest; ad hoc approach", "level_2": "Basic encryption at rest in development", "level_3": "Encryption at Rest exists but gaps remain", "level_4": "Comprehensive encryption at rest well-implemented", "level_5": "Industry-leading encryption at rest with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Security', 'D5-Q027', 'Is data encrypted in transit for all AI system communications?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No encryption in transit in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic encryption in transit in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Encryption in Transit exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive encryption in transit with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading encryption in transit with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating encryption in transit maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal encryption in transit; ad hoc approach", "level_2": "Basic encryption in transit in development", "level_3": "Encryption in Transit exists but gaps remain", "level_4": "Comprehensive encryption in transit well-implemented", "level_5": "Industry-leading encryption in transit with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Security', 'D5-Q028', 'Do you have secure cryptographic key management for AI data encryption?', 'HIGH', 1.0, '[{"value": 1, "label": "No key management in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic key management in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Key Management exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive key management with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading key management with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating key management maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal key management; ad hoc approach", "level_2": "Basic key management in development", "level_3": "Key Management exists but gaps remain", "level_4": "Comprehensive key management well-implemented", "level_5": "Industry-leading key management with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Security', 'D5-Q029', 'Are secure data disposal procedures in place for AI system data?', 'HIGH', 1.0, '[{"value": 1, "label": "No secure data disposal in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic secure data disposal in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Secure Data Disposal exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive secure data disposal with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading secure data disposal with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating secure data disposal maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal secure data disposal; ad hoc approach", "level_2": "Basic secure data disposal in development", "level_3": "Secure Data Disposal exists but gaps remain", "level_4": "Comprehensive secure data disposal well-implemented", "level_5": "Industry-leading secure data disposal with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Data Security', 'D5-Q030', 'Do you have a data breach response plan specific to AI systems?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No breach response in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic breach response in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Breach Response exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive breach response with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading breach response with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating breach response maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal breach response; ad hoc approach", "level_2": "Basic breach response in development", "level_3": "Breach Response exists but gaps remain", "level_4": "Comprehensive breach response well-implemented", "level_5": "Industry-leading breach response with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Cross-Border Flows', 'D5-Q031', 'Are appropriate legal mechanisms in place for cross-border AI data transfers?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No transfer mechanisms in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic transfer mechanisms in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Transfer Mechanisms exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive transfer mechanisms with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading transfer mechanisms with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating transfer mechanisms maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal transfer mechanisms; ad hoc approach", "level_2": "Basic transfer mechanisms in development", "level_3": "Transfer Mechanisms exists but gaps remain", "level_4": "Comprehensive transfer mechanisms well-implemented", "level_5": "Industry-leading transfer mechanisms with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Cross-Border Flows', 'D5-Q032', 'Do you comply with data localization requirements for AI systems?', 'HIGH', 1.0, '[{"value": 1, "label": "No data localization in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data localization in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Localization exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data localization with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data localization with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data localization maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data localization; ad hoc approach", "level_2": "Basic data localization in development", "level_3": "Data Localization exists but gaps remain", "level_4": "Comprehensive data localization well-implemented", "level_5": "Industry-leading data localization with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Cross-Border Flows', 'D5-Q033', 'Are risk assessments conducted for cross-border AI data transfers?', 'HIGH', 1.0, '[{"value": 1, "label": "No transfer risk assessments in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic transfer risk assessments in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Transfer Risk Assessments exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive transfer risk assessments with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading transfer risk assessments with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating transfer risk assessments maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal transfer risk assessments; ad hoc approach", "level_2": "Basic transfer risk assessments in development", "level_3": "Transfer Risk Assessments exists but gaps remain", "level_4": "Comprehensive transfer risk assessments well-implemented", "level_5": "Industry-leading transfer risk assessments with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Cross-Border Flows', 'D5-Q034', 'Do you verify adequacy determinations for international AI data transfers?', 'HIGH', 1.0, '[{"value": 1, "label": "No adequacy determinations in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic adequacy determinations in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Adequacy Determinations exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive adequacy determinations with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading adequacy determinations with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating adequacy determinations maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal adequacy determinations; ad hoc approach", "level_2": "Basic adequacy determinations in development", "level_3": "Adequacy Determinations exists but gaps remain", "level_4": "Comprehensive adequacy determinations well-implemented", "level_5": "Industry-leading adequacy determinations with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Cross-Border Flows', 'D5-Q035', 'Do you respect data sovereignty requirements in AI system deployments?', 'HIGH', 1.0, '[{"value": 1, "label": "No data sovereignty in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data sovereignty in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Sovereignty exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data sovereignty with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data sovereignty with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data sovereignty maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data sovereignty; ad hoc approach", "level_2": "Basic data sovereignty in development", "level_3": "Data Sovereignty exists but gaps remain", "level_4": "Comprehensive data sovereignty well-implemented", "level_5": "Industry-leading data sovereignty with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Vendor Management', 'D5-Q036', 'Do you have data processing agreements with all AI system vendors?', 'CRITICAL', 1.5, '[{"value": 1, "label": "No processor agreements in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic processor agreements in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Processor Agreements exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive processor agreements with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading processor agreements with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating processor agreements maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal processor agreements; ad hoc approach", "level_2": "Basic processor agreements in development", "level_3": "Processor Agreements exists but gaps remain", "level_4": "Comprehensive processor agreements well-implemented", "level_5": "Industry-leading processor agreements with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Vendor Management', 'D5-Q037', 'Are security assessments conducted for all AI vendors handling data?', 'HIGH', 1.0, '[{"value": 1, "label": "No vendor security assessments in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic vendor security assessments in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Vendor Security Assessments exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive vendor security assessments with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading vendor security assessments with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating vendor security assessments maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal vendor security assessments; ad hoc approach", "level_2": "Basic vendor security assessments in development", "level_3": "Vendor Security Assessments exists but gaps remain", "level_4": "Comprehensive vendor security assessments well-implemented", "level_5": "Industry-leading vendor security assessments with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Vendor Management', 'D5-Q038', 'Do your vendor contracts include audit rights for AI data processing?', 'HIGH', 1.0, '[{"value": 1, "label": "No audit rights in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic audit rights in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Audit Rights exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive audit rights with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading audit rights with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating audit rights maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal audit rights; ad hoc approach", "level_2": "Basic audit rights in development", "level_3": "Audit Rights exists but gaps remain", "level_4": "Comprehensive audit rights well-implemented", "level_5": "Industry-leading audit rights with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Vendor Management', 'D5-Q039', 'Are DPAs in place with all AI vendors processing personal data?', 'HIGH', 1.0, '[{"value": 1, "label": "No data processing addendums in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic data processing addendums in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Data Processing Addendums exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive data processing addendums with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading data processing addendums with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating data processing addendums maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal data processing addendums; ad hoc approach", "level_2": "Basic data processing addendums in development", "level_3": "Data Processing Addendums exists but gaps remain", "level_4": "Comprehensive data processing addendums well-implemented", "level_5": "Industry-leading data processing addendums with innovation"}}', '{}', '[]', '{}');

INSERT INTO questions (domain_id, subdomain, question_code, question_text, criticality, scoring_weight, response_options, evidence_requirements, assessor_guidance, industry_variations, related_questions, regulatory_context)
VALUES (5, 'Vendor Management', 'D5-Q040', 'Do vendor contracts include breach notification requirements for AI systems?', 'HIGH', 1.0, '[{"value": 1, "label": "No breach notification in place", "score": 1.0, "maturity_level": 1}, {"value": 2, "label": "Basic breach notification in early stages", "score": 2.0, "maturity_level": 2}, {"value": 3, "label": "Breach Notification exists but inconsistently applied", "score": 3.0, "maturity_level": 3}, {"value": 4, "label": "Comprehensive breach notification with good enforcement", "score": 4.0, "maturity_level": 4}, {"value": 5, "label": "Industry-leading breach notification with continuous improvement", "score": 5.0, "maturity_level": 5}]', '{"required": true, "guidance": "Provide documentation, implementation evidence, metrics, and examples demonstrating breach notification maturity."}', '{"guidance": "Evaluate: 1) Comprehensiveness, 2) Implementation quality, 3) Enforcement mechanisms, 4) Continuous improvement, 5) Alignment with best practices.", "maturity_indicators": {"level_1": "No formal breach notification; ad hoc approach", "level_2": "Basic breach notification in development", "level_3": "Breach Notification exists but gaps remain", "level_4": "Comprehensive breach notification well-implemented", "level_5": "Industry-leading breach notification with innovation"}}', '{}', '[]', '{}');

-- ================================================================================
-- DOMAIN 5 COMPLETE: 40/40 questions
-- ================================================================================
